<?php

use Illuminate\Database\Seeder;

class CategoryTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('category')->delete();
        
        \DB::table('category')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Additional Photos',
                'company_id' => 1,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-10-09 14:56:20',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Inspection Area_1',
                'company_id' => 1,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-09 15:05:21',
                'updated_at' => '2019-10-23 10:06:26',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 7,
                'name' => 'Additional Photos',
                'company_id' => 2,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-10-09 17:22:49',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 8,
                'name' => 'Additional Photos',
                'company_id' => 2,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-10-09 17:23:01',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 9,
                'name' => 'Additional Photos',
                'company_id' => 2,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-10-09 17:23:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 10,
                'name' => 'airport inspection area',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-10-09 17:32:08',
                'updated_at' => '2019-11-05 17:46:54',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'name' => 'highway inspection area',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-09 17:32:36',
                'updated_at' => '2019-11-05 17:46:54',
                'deleted_at' => '2020-01-02 13:04:57',
            ),
            7 => 
            array (
                'id' => 12,
                'name' => 'railway inspection area',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-10-09 17:33:47',
                'updated_at' => '2019-10-23 11:39:12',
                'deleted_at' => '2020-01-02 13:05:04',
            ),
            8 => 
            array (
                'id' => 15,
                'name' => 'airport photo view',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 10,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => 3,
                'created_at' => '2019-10-09 17:41:16',
                'updated_at' => '2019-10-10 11:40:29',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 16,
                'name' => 'railway photo view',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 12,
                'min_quantity' => 2,
                'thumbnail' => 1,
                'order_by' => 2,
                'created_at' => '2019-10-09 17:46:26',
                'updated_at' => '2019-10-10 11:40:39',
                'deleted_at' => '2020-01-02 13:05:04',
            ),
            10 => 
            array (
                'id' => 17,
                'name' => 'highway photo view',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 11,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-09 17:47:10',
                'updated_at' => '2019-10-10 11:40:38',
                'deleted_at' => '2020-01-02 13:04:57',
            ),
            11 => 
            array (
                'id' => 18,
                'name' => 'airport required photo',
                'company_id' => 2,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-10-09 17:56:10',
                'updated_at' => '2019-11-04 19:12:35',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 22,
                'name' => 'railway required photo',
                'company_id' => 2,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-10-09 18:07:57',
                'updated_at' => '2019-10-23 14:16:02',
                'deleted_at' => '2020-01-02 13:05:50',
            ),
            13 => 
            array (
                'id' => 23,
                'name' => 'highway required photo',
                'company_id' => 2,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-10-09 18:08:25',
                'updated_at' => '2019-10-23 16:52:09',
                'deleted_at' => '2020-01-02 13:05:54',
            ),
            14 => 
            array (
                'id' => 34,
                'name' => 'Additional Photos',
                'company_id' => 3,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-10-14 17:07:59',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 35,
                'name' => 'Roofing',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-14 17:29:57',
                'updated_at' => '2019-10-14 17:29:57',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 36,
                'name' => 'Front Elevation',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-10-14 17:31:34',
                'updated_at' => '2019-10-14 17:31:34',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 37,
                'name' => 'Right Elevation',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-10-14 17:31:45',
                'updated_at' => '2019-10-14 17:31:45',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 38,
                'name' => 'Rear Elevation',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-10-14 17:31:54',
                'updated_at' => '2019-10-14 17:31:54',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 39,
                'name' => 'Left Elevation',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 5,
                'created_at' => '2019-10-14 17:32:09',
                'updated_at' => '2019-10-14 17:32:09',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 40,
                'name' => 'Other Structures',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 6,
                'created_at' => '2019-10-14 17:32:23',
                'updated_at' => '2019-10-14 17:32:23',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 41,
                'name' => 'Production',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 7,
                'created_at' => '2019-10-14 17:32:35',
                'updated_at' => '2019-10-14 17:32:35',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 42,
                'name' => 'Driveway',
                'company_id' => 3,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-14 17:33:18',
                'updated_at' => '2019-10-14 17:34:04',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 43,
                'name' => 'Front Overview',
                'company_id' => 3,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => 2,
                'created_at' => '2019-10-14 17:33:35',
                'updated_at' => '2019-10-14 17:34:04',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 44,
                'name' => 'Right Overview',
                'company_id' => 3,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-10-14 17:34:18',
                'updated_at' => '2019-10-14 17:34:18',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 45,
                'name' => 'Rear Overview',
                'company_id' => 3,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-10-14 17:34:34',
                'updated_at' => '2019-10-14 17:34:34',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 46,
                'name' => 'Left Overview',
                'company_id' => 3,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 5,
                'created_at' => '2019-10-14 17:34:48',
                'updated_at' => '2019-10-14 17:34:48',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 47,
                'name' => 'Soffit Width Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-14 17:44:36',
                'updated_at' => '2019-10-14 18:00:20',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 48,
                'name' => 'Eave Metal Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-10-14 17:44:50',
                'updated_at' => '2019-10-14 17:52:05',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 49,
                'name' => 'Sheathing Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-10-14 17:45:03',
                'updated_at' => '2019-10-14 18:00:30',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 50,
                'name' => 'Comp Layers Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-10-14 17:45:19',
                'updated_at' => '2019-10-14 18:00:34',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 51,
                'name' => 'Wood Layers Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 5,
                'created_at' => '2019-10-14 17:45:39',
                'updated_at' => '2019-10-14 18:01:16',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 52,
                'name' => 'IWS on Eaves Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 6,
                'created_at' => '2019-10-14 17:45:59',
                'updated_at' => '2019-10-14 18:01:17',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 53,
                'name' => 'Haag Gauge Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 7,
                'created_at' => '2019-10-14 17:46:34',
                'updated_at' => '2019-10-14 18:01:40',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 54,
                'name' => 'Pitch Gauge Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 8,
                'created_at' => '2019-10-14 17:47:23',
                'updated_at' => '2019-10-14 18:03:43',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 55,
                'name' => 'Rake Metal Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 9,
                'created_at' => '2019-10-14 17:49:32',
                'updated_at' => '2019-10-14 18:03:53',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 56,
                'name' => 'Shingle Damage Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 10,
                'created_at' => '2019-10-14 17:51:13',
                'updated_at' => '2019-10-14 18:04:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 57,
                'name' => 'Ridge Cap Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 11,
                'created_at' => '2019-10-14 17:52:36',
                'updated_at' => '2019-10-14 18:04:19',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 58,
                'name' => 'Ventilation Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 12,
                'created_at' => '2019-10-14 17:53:25',
                'updated_at' => '2019-10-14 18:04:19',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 59,
                'name' => 'Chimney Flashing Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 13,
                'created_at' => '2019-10-14 17:53:41',
                'updated_at' => '2019-10-14 18:04:20',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 60,
                'name' => 'PIpe Flashing Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 14,
                'created_at' => '2019-10-14 17:53:52',
                'updated_at' => '2019-10-14 18:04:46',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 61,
                'name' => 'Skylight Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 15,
                'created_at' => '2019-10-14 17:54:06',
                'updated_at' => '2019-10-14 18:05:06',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 62,
                'name' => 'Valley Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 16,
                'created_at' => '2019-10-14 17:54:23',
                'updated_at' => '2019-10-14 18:05:13',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 63,
                'name' => 'Step Flashing Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 17,
                'created_at' => '2019-10-14 17:54:41',
                'updated_at' => '2019-10-14 18:05:21',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 64,
                'name' => 'Counter Flashing Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 18,
                'created_at' => '2019-10-14 17:54:53',
                'updated_at' => '2019-10-14 18:05:21',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 65,
                'name' => 'Satelite Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 19,
                'created_at' => '2019-10-14 17:55:06',
                'updated_at' => '2019-10-14 18:05:21',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 66,
                'name' => 'Meter Mast',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 20,
                'created_at' => '2019-10-14 17:55:17',
                'updated_at' => '2019-10-14 18:05:31',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 67,
                'name' => 'Flat Roofing Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 21,
                'created_at' => '2019-10-14 17:55:30',
                'updated_at' => '2019-10-14 18:05:48',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 68,
                'name' => 'Rafter Spacing Photos',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 22,
                'created_at' => '2019-10-14 17:55:42',
                'updated_at' => '2019-10-14 18:05:48',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 69,
                'name' => 'Other Roof Coverings',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-10-16 19:07:56',
                'updated_at' => '2019-10-16 19:08:08',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 70,
                'name' => 'Roof Overview',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 35,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-10-16 20:52:20',
                'updated_at' => '2019-10-16 20:52:34',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 75,
                'name' => 'Additional Photos',
                'company_id' => 2,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-10-23 11:28:08',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 76,
                'name' => 'fire inspection area',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-10-23 11:39:05',
                'updated_at' => '2019-11-08 19:46:40',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 77,
                'name' => 'fire photo view',
                'company_id' => 2,
                'type' => 2,
                'parent_id' => 76,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-10-23 11:40:36',
                'updated_at' => '2020-01-20 15:37:06',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 78,
                'name' => 'Req Photo',
                'company_id' => 1,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => NULL,
                'created_at' => '2019-10-23 13:31:04',
                'updated_at' => '2019-10-23 13:34:08',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 79,
                'name' => 'fire required photo',
                'company_id' => 2,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => NULL,
                'created_at' => '2019-10-23 13:37:31',
                'updated_at' => '2020-01-20 15:37:32',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 80,
                'name' => 'Gutters',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 36,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-24 18:23:22',
                'updated_at' => '2019-10-24 20:11:52',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 81,
                'name' => 'Downspouts',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 36,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-10-24 18:23:51',
                'updated_at' => '2019-10-24 20:11:52',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 82,
                'name' => 'Siding',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 36,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-10-24 18:25:20',
                'updated_at' => '2019-10-24 20:11:52',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 83,
                'name' => 'Paint/ Stain',
                'company_id' => 3,
                'type' => 2,
                'parent_id' => 36,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-10-24 18:25:43',
                'updated_at' => '2019-10-24 20:11:52',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 84,
                'name' => 'Additional Photos',
                'company_id' => 4,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-10-28 07:36:40',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 85,
                'name' => 'KCK',
                'company_id' => 4,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-28 07:39:09',
                'updated_at' => '2019-10-28 07:39:09',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 86,
                'name' => 'KCK Test',
                'company_id' => 4,
                'type' => 2,
                'parent_id' => 85,
                'min_quantity' => 4,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-10-28 07:39:41',
                'updated_at' => '2019-10-28 07:39:41',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 87,
                'name' => 'KCK Roof',
                'company_id' => 4,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 2,
                'thumbnail' => 1,
                'order_by' => 1,
                'created_at' => '2019-10-28 07:40:04',
                'updated_at' => '2019-10-28 07:40:04',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 89,
                'name' => 'Additional Photos',
                'company_id' => 2,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-11-08 19:45:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 100,
                'name' => 'Test Area',
                'company_id' => 1,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-12 14:11:00',
                'updated_at' => '2019-11-12 14:11:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 101,
                'name' => 'Test Area',
                'company_id' => 1,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-12 14:12:32',
                'updated_at' => '2019-11-12 14:12:32',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 102,
                'name' => 'Test Area',
                'company_id' => 1,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-11-12 14:12:47',
                'updated_at' => '2019-11-12 14:12:47',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 103,
                'name' => 'Tony2 Stark',
                'company_id' => 1,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 5,
                'created_at' => '2019-11-12 14:13:36',
                'updated_at' => '2019-11-12 14:13:36',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 104,
                'name' => 'Tony2 Stark',
                'company_id' => 1,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 6,
                'created_at' => '2019-11-12 17:34:25',
                'updated_at' => '2019-11-12 17:34:25',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 106,
                'name' => 'Additional Photos',
                'company_id' => 7,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-11-13 12:08:24',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 107,
                'name' => 'floor',
                'company_id' => 7,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-13 12:10:23',
                'updated_at' => '2019-11-13 12:10:23',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 108,
                'name' => 'floor photo view',
                'company_id' => 7,
                'type' => 2,
                'parent_id' => 107,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-13 12:11:14',
                'updated_at' => '2019-11-13 12:11:14',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 109,
                'name' => 'floor required photo',
                'company_id' => 7,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-13 12:12:02',
                'updated_at' => '2019-11-13 12:12:02',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 110,
                'name' => 'Additional Photos',
                'company_id' => 8,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-11-13 20:20:24',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 111,
                'name' => 'Roofing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-13 20:22:17',
                'updated_at' => '2019-12-16 19:12:01',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 112,
                'name' => 'Front Elevation',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-13 20:22:32',
                'updated_at' => '2019-12-16 19:12:01',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 113,
                'name' => 'Right Elevation',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-13 20:22:43',
                'updated_at' => '2019-12-16 19:12:01',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 114,
                'name' => 'Rear Elevation',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-11-13 20:22:54',
                'updated_at' => '2019-12-16 19:12:01',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 115,
                'name' => 'Left Elevation',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 5,
                'created_at' => '2019-11-13 20:23:03',
                'updated_at' => '2019-12-16 19:12:01',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 116,
                'name' => 'Other Structures',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 6,
                'created_at' => '2019-11-13 20:23:17',
                'updated_at' => '2019-12-16 19:12:01',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 117,
                'name' => 'Production',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 8,
                'created_at' => '2019-11-13 20:23:27',
                'updated_at' => '2019-12-16 22:31:28',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 118,
                'name' => 'Driveway',
                'company_id' => 8,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-13 20:24:03',
                'updated_at' => '2019-12-16 21:05:17',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 119,
                'name' => '2+ Stories',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 31,
                'created_at' => '2019-11-13 20:25:19',
                'updated_at' => '2019-12-16 20:12:29',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 120,
                'name' => 'Soffit Width',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 21,
                'created_at' => '2019-11-13 20:53:23',
                'updated_at' => '2019-12-16 20:09:28',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 121,
                'name' => 'Eave Metal',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 23,
                'created_at' => '2019-11-13 20:53:42',
                'updated_at' => '2019-12-16 20:10:22',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 122,
                'name' => 'Sheathing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 22,
                'created_at' => '2019-11-13 20:53:55',
                'updated_at' => '2019-12-16 20:10:22',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 123,
                'name' => 'Comp Layers',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 25,
                'created_at' => '2019-11-13 20:54:14',
                'updated_at' => '2019-12-16 20:10:22',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 124,
                'name' => 'Wood Layers',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 26,
                'created_at' => '2019-11-13 20:54:23',
                'updated_at' => '2019-12-16 20:10:22',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 125,
                'name' => 'IWS on Eaves',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 24,
                'created_at' => '2019-11-13 20:54:50',
                'updated_at' => '2019-12-16 20:10:22',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 126,
                'name' => 'Haag Gauge',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 27,
                'created_at' => '2019-11-13 20:55:09',
                'updated_at' => '2019-12-16 20:10:22',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 127,
                'name' => 'Pitch Gauge',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 29,
                'created_at' => '2019-11-13 21:20:42',
                'updated_at' => '2019-12-16 20:11:31',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 128,
                'name' => 'Rake Metal',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 30,
                'created_at' => '2019-11-13 21:20:55',
                'updated_at' => '2019-12-16 20:11:31',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 129,
                'name' => 'Shingle Damage',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 32,
                'created_at' => '2019-11-13 21:21:10',
                'updated_at' => '2019-12-16 20:12:29',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 130,
                'name' => 'Ridge Cap',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 28,
                'created_at' => '2019-11-13 21:21:20',
                'updated_at' => '2019-12-16 20:11:31',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 131,
                'name' => 'Ventilation',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 37,
                'created_at' => '2019-11-13 21:21:30',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 132,
                'name' => 'Chimney Flashing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 38,
                'created_at' => '2019-11-13 21:21:39',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 133,
                'name' => 'Pipe Flashings',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 41,
                'created_at' => '2019-11-13 21:21:50',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 134,
                'name' => 'Skylights',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 36,
                'created_at' => '2019-11-13 21:22:11',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 135,
                'name' => 'Valleys',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 33,
                'created_at' => '2019-11-13 21:22:19',
                'updated_at' => '2019-12-16 20:14:12',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 136,
                'name' => 'Step Flashing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 39,
                'created_at' => '2019-11-13 21:22:28',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 137,
                'name' => 'Counter Flashing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 40,
                'created_at' => '2019-11-13 21:22:42',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 138,
                'name' => 'Satelite Dishes',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 35,
                'created_at' => '2019-11-13 21:23:05',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 139,
                'name' => 'Meter Mast',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 34,
                'created_at' => '2019-11-13 21:23:14',
                'updated_at' => '2019-12-16 20:15:06',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 140,
                'name' => 'Low Slope Roofing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 42,
                'created_at' => '2019-11-13 21:23:24',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 141,
                'name' => 'Rafter Spacing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 43,
                'created_at' => '2019-11-13 21:23:36',
                'updated_at' => '2019-12-16 20:15:18',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 143,
                'name' => 'Cornice Returns and Strips',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 20,
                'created_at' => '2019-11-13 23:35:48',
                'updated_at' => '2019-12-16 20:09:27',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 144,
                'name' => 'Ground Items',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 7,
                'created_at' => '2019-11-15 00:36:50',
                'updated_at' => '2019-12-16 19:12:06',
                'deleted_at' => '2019-12-16 19:12:30',
            ),
            108 => 
            array (
                'id' => 145,
                'name' => 'Gutters',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-11-15 05:53:08',
                'updated_at' => '2019-12-16 19:44:23',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 146,
                'name' => 'Gutter Protection',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-11-15 05:54:22',
                'updated_at' => '2019-12-16 19:42:46',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 147,
                'name' => 'Downspouts',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-11-15 05:54:38',
                'updated_at' => '2019-12-16 19:42:58',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 148,
                'name' => 'Window Screens',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 5,
                'created_at' => '2019-11-15 05:55:16',
                'updated_at' => '2019-12-16 20:08:30',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 149,
                'name' => 'Window Reglazing',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 6,
                'created_at' => '2019-11-15 05:55:29',
                'updated_at' => '2019-12-16 20:08:30',
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 150,
                'name' => 'Window Awnings',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 7,
                'created_at' => '2019-11-15 05:56:42',
                'updated_at' => '2019-12-16 20:08:31',
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 151,
                'name' => 'Single Garage Doors',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 8,
                'created_at' => '2019-11-15 05:57:17',
                'updated_at' => '2019-12-16 20:07:19',
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 152,
                'name' => 'Double Garage Doors',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 9,
                'created_at' => '2019-11-15 05:57:44',
                'updated_at' => '2019-12-16 20:07:19',
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 153,
                'name' => 'Storm Doors',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 7,
                'created_at' => '2019-11-15 05:58:04',
                'updated_at' => '2019-12-16 20:07:19',
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 154,
                'name' => 'A/C Units',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 19,
                'created_at' => '2019-11-15 05:58:38',
                'updated_at' => '2019-12-16 20:08:20',
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 155,
                'name' => 'photo view',
                'company_id' => 1,
                'type' => 2,
                'parent_id' => 2,
                'min_quantity' => 2,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-15 14:01:06',
                'updated_at' => '2019-11-15 14:01:06',
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 160,
                'name' => 'required photo 2',
                'company_id' => 1,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 15,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-25 17:02:59',
                'updated_at' => '2019-11-25 17:02:59',
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 177,
                'name' => 'roof',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-11-26 16:07:01',
                'updated_at' => '2019-12-02 14:29:19',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            121 => 
            array (
                'id' => 178,
                'name' => 'roof photo view',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-26 16:07:16',
                'updated_at' => '2019-11-26 16:07:16',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            122 => 
            array (
                'id' => 179,
                'name' => 'roof 2',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-26 16:07:28',
                'updated_at' => '2019-11-26 16:07:28',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            123 => 
            array (
                'id' => 180,
                'name' => 'roof3',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-26 16:07:42',
                'updated_at' => '2019-11-26 16:07:42',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            124 => 
            array (
                'id' => 181,
                'name' => 'roof required photo',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => 1,
                'created_at' => '2019-11-26 16:08:22',
                'updated_at' => '2019-11-26 16:08:22',
                'deleted_at' => '2019-11-28 12:52:38',
            ),
            125 => 
            array (
                'id' => 182,
                'name' => 'roof req 2',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-26 16:09:04',
                'updated_at' => '2019-11-26 16:09:04',
                'deleted_at' => '2019-11-28 12:52:42',
            ),
            126 => 
            array (
                'id' => 183,
                'name' => 'roof req 3',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-26 16:09:18',
                'updated_at' => '2019-11-26 16:09:18',
                'deleted_at' => '2019-11-27 18:04:07',
            ),
            127 => 
            array (
                'id' => 184,
                'name' => 'roof req 3',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-27 18:04:48',
                'updated_at' => '2019-11-27 18:04:48',
                'deleted_at' => '2019-11-28 12:52:46',
            ),
            128 => 
            array (
                'id' => 185,
                'name' => 'req1',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => 1,
                'created_at' => '2019-11-28 12:53:50',
                'updated_at' => '2019-11-28 12:53:50',
                'deleted_at' => '2019-11-28 14:23:42',
            ),
            129 => 
            array (
                'id' => 186,
                'name' => 'req2',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-28 12:54:17',
                'updated_at' => '2019-11-28 12:54:17',
                'deleted_at' => '2019-11-28 14:23:45',
            ),
            130 => 
            array (
                'id' => 187,
                'name' => 'req3',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-28 12:54:29',
                'updated_at' => '2019-11-28 12:54:29',
                'deleted_at' => '2019-11-28 14:23:49',
            ),
            131 => 
            array (
                'id' => 188,
                'name' => 'photo view 1',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-28 14:24:48',
                'updated_at' => '2019-11-28 14:24:48',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            132 => 
            array (
                'id' => 189,
                'name' => 'photo view 2',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-28 14:24:58',
                'updated_at' => '2019-11-28 14:24:58',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            133 => 
            array (
                'id' => 190,
                'name' => 'photo view 3',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-28 14:25:14',
                'updated_at' => '2019-11-28 14:25:14',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            134 => 
            array (
                'id' => 191,
                'name' => 'photo view 1',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-28 14:48:10',
                'updated_at' => '2019-11-28 14:48:10',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            135 => 
            array (
                'id' => 192,
                'name' => 'photo view 2',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-28 14:48:21',
                'updated_at' => '2019-11-28 14:48:21',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            136 => 
            array (
                'id' => 193,
                'name' => 'photo view 3',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 177,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-11-28 14:48:31',
                'updated_at' => '2019-11-28 14:48:31',
                'deleted_at' => '2019-12-02 14:30:01',
            ),
            137 => 
            array (
                'id' => 194,
                'name' => 'req1',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => NULL,
                'created_at' => '2019-11-28 15:08:55',
                'updated_at' => '2019-11-28 15:11:03',
                'deleted_at' => '2019-12-02 14:34:06',
            ),
            138 => 
            array (
                'id' => 195,
                'name' => 'Additional Photos',
                'company_id' => 6,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-11-28 15:10:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 196,
                'name' => 'req2',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-11-28 15:11:49',
                'updated_at' => '2019-11-28 15:11:49',
                'deleted_at' => '2019-12-02 14:34:11',
            ),
            140 => 
            array (
                'id' => 197,
                'name' => 'req3',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-11-28 15:12:05',
                'updated_at' => '2019-11-28 15:12:05',
                'deleted_at' => '2019-12-02 14:34:15',
            ),
            141 => 
            array (
                'id' => 198,
                'name' => 'Additional Photos',
                'company_id' => 6,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-12-02 14:31:37',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 199,
                'name' => 'new inspection area',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-12-02 14:32:40',
                'updated_at' => '2019-12-02 14:32:40',
                'deleted_at' => '2019-12-05 12:25:38',
            ),
            143 => 
            array (
                'id' => 200,
                'name' => 'photo view 1',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 199,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-12-02 14:33:15',
                'updated_at' => '2019-12-02 14:33:47',
                'deleted_at' => '2019-12-05 12:25:38',
            ),
            144 => 
            array (
                'id' => 201,
                'name' => 'photo view 2',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 199,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 2,
                'created_at' => '2019-12-02 14:33:28',
                'updated_at' => '2019-12-02 14:33:28',
                'deleted_at' => '2019-12-05 12:25:38',
            ),
            145 => 
            array (
                'id' => 202,
                'name' => 'required photo 1',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => 1,
                'created_at' => '2019-12-02 14:35:14',
                'updated_at' => '2019-12-02 14:35:14',
                'deleted_at' => '2019-12-02 14:40:42',
            ),
            146 => 
            array (
                'id' => 203,
                'name' => 'required photo 2',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => NULL,
                'created_at' => '2019-12-02 14:35:30',
                'updated_at' => '2019-12-02 18:42:08',
                'deleted_at' => '2019-12-05 12:25:51',
            ),
            147 => 
            array (
                'id' => 204,
                'name' => 'required photo 1',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-12-02 14:41:07',
                'updated_at' => '2019-12-02 14:41:07',
                'deleted_at' => '2019-12-05 12:25:58',
            ),
            148 => 
            array (
                'id' => 205,
                'name' => 'photo view 3',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 199,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-12-03 15:40:44',
                'updated_at' => '2019-12-03 15:40:44',
                'deleted_at' => '2019-12-05 12:25:38',
            ),
            149 => 
            array (
                'id' => 206,
                'name' => 'required photo 3',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-12-03 19:18:24',
                'updated_at' => '2019-12-03 19:27:21',
                'deleted_at' => '2019-12-05 12:25:54',
            ),
            150 => 
            array (
                'id' => 207,
                'name' => 'Additional Photos',
                'company_id' => 6,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2019-12-05 12:27:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            151 => 
            array (
                'id' => 208,
                'name' => 'final Isnpection area',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-12-05 12:27:55',
                'updated_at' => '2019-12-05 12:27:55',
                'deleted_at' => NULL,
            ),
            152 => 
            array (
                'id' => 209,
                'name' => 'final photo view 1',
                'company_id' => 6,
                'type' => 2,
                'parent_id' => 208,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2019-12-05 12:32:34',
                'updated_at' => '2019-12-05 12:32:34',
                'deleted_at' => NULL,
            ),
            153 => 
            array (
                'id' => 210,
                'name' => 'final required photo',
                'company_id' => 6,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => 1,
                'created_at' => '2019-12-05 12:34:04',
                'updated_at' => '2019-12-05 12:34:04',
                'deleted_at' => NULL,
            ),
            154 => 
            array (
                'id' => 211,
                'name' => 'Paint/ Stain Damage',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 10,
                'created_at' => '2019-12-16 19:45:31',
                'updated_at' => '2019-12-16 20:06:56',
                'deleted_at' => NULL,
            ),
            155 => 
            array (
                'id' => 212,
                'name' => 'Siding',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 11,
                'created_at' => '2019-12-16 19:47:29',
                'updated_at' => '2019-12-16 20:06:56',
                'deleted_at' => NULL,
            ),
            156 => 
            array (
                'id' => 213,
                'name' => 'Fascia & Soffit',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 14,
                'created_at' => '2019-12-16 19:49:06',
                'updated_at' => '2019-12-16 20:07:07',
                'deleted_at' => NULL,
            ),
            157 => 
            array (
                'id' => 214,
                'name' => 'Light Fixtures',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 16,
                'created_at' => '2019-12-16 19:49:46',
                'updated_at' => '2019-12-16 20:08:20',
                'deleted_at' => NULL,
            ),
            158 => 
            array (
                'id' => 215,
                'name' => 'Shutters',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 13,
                'created_at' => '2019-12-16 19:53:38',
                'updated_at' => '2019-12-16 20:07:07',
                'deleted_at' => NULL,
            ),
            159 => 
            array (
                'id' => 216,
                'name' => 'Window/ Door Wraps',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 12,
                'created_at' => '2019-12-16 20:02:58',
                'updated_at' => '2019-12-16 20:06:56',
                'deleted_at' => NULL,
            ),
            160 => 
            array (
                'id' => 217,
                'name' => 'Decks',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 17,
                'created_at' => '2019-12-16 20:05:39',
                'updated_at' => '2019-12-16 20:08:20',
                'deleted_at' => NULL,
            ),
            161 => 
            array (
                'id' => 218,
                'name' => 'Fences',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 18,
                'created_at' => '2019-12-16 20:05:48',
                'updated_at' => '2019-12-16 20:08:20',
                'deleted_at' => NULL,
            ),
            162 => 
            array (
                'id' => 219,
                'name' => 'Windows',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-12-16 20:07:35',
                'updated_at' => '2019-12-16 20:08:30',
                'deleted_at' => NULL,
            ),
            163 => 
            array (
                'id' => 220,
                'name' => 'Front Overview',
                'company_id' => 8,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 1,
                'order_by' => 2,
                'created_at' => '2019-12-16 20:16:39',
                'updated_at' => '2019-12-16 21:05:17',
                'deleted_at' => NULL,
            ),
            164 => 
            array (
                'id' => 221,
                'name' => 'Right Overview',
                'company_id' => 8,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 4,
                'created_at' => '2019-12-16 20:16:54',
                'updated_at' => '2019-12-16 20:17:45',
                'deleted_at' => NULL,
            ),
            165 => 
            array (
                'id' => 222,
                'name' => 'Rear Overview',
                'company_id' => 8,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 5,
                'created_at' => '2019-12-16 20:17:07',
                'updated_at' => '2019-12-16 20:17:45',
                'deleted_at' => NULL,
            ),
            166 => 
            array (
                'id' => 223,
                'name' => 'Left Overview',
                'company_id' => 8,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 6,
                'created_at' => '2019-12-16 20:17:20',
                'updated_at' => '2019-12-16 20:17:45',
                'deleted_at' => NULL,
            ),
            167 => 
            array (
                'id' => 224,
                'name' => 'House Numbers',
                'company_id' => 8,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 1,
                'thumbnail' => 0,
                'order_by' => 3,
                'created_at' => '2019-12-16 20:17:39',
                'updated_at' => '2019-12-16 21:05:17',
                'deleted_at' => NULL,
            ),
            168 => 
            array (
                'id' => 225,
                'name' => 'Siding Accessories',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-12-16 22:28:42',
                'updated_at' => '2019-12-16 22:29:03',
                'deleted_at' => NULL,
            ),
            169 => 
            array (
                'id' => 226,
                'name' => 'Interior',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 7,
                'created_at' => '2019-12-16 22:31:17',
                'updated_at' => '2019-12-16 22:31:28',
                'deleted_at' => NULL,
            ),
            170 => 
            array (
                'id' => 227,
                'name' => 'Interior Damage',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 226,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-12-16 22:32:55',
                'updated_at' => '2019-12-16 22:33:11',
                'deleted_at' => NULL,
            ),
            171 => 
            array (
                'id' => 228,
                'name' => 'Starter',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-12-16 23:00:28',
                'updated_at' => '2019-12-16 23:00:43',
                'deleted_at' => NULL,
            ),
            172 => 
            array (
                'id' => 229,
                'name' => 'Half Ridge',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 111,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-12-16 23:06:36',
                'updated_at' => '2019-12-16 23:06:48',
                'deleted_at' => NULL,
            ),
            173 => 
            array (
                'id' => 230,
                'name' => 'Intake Ventilation',
                'company_id' => 8,
                'type' => 2,
                'parent_id' => 112,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => NULL,
                'created_at' => '2019-12-16 23:15:08',
                'updated_at' => '2019-12-16 23:15:28',
                'deleted_at' => NULL,
            ),
            174 => 
            array (
                'id' => 231,
                'name' => 'Additional Photos',
                'company_id' => 10,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2020-01-10 16:19:53',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            175 => 
            array (
                'id' => 232,
                'name' => 'washroom',
                'company_id' => 10,
                'type' => 2,
                'parent_id' => 0,
                'min_quantity' => NULL,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2020-01-10 16:21:28',
                'updated_at' => '2020-01-10 16:21:28',
                'deleted_at' => NULL,
            ),
            176 => 
            array (
                'id' => 233,
                'name' => 'washroom photo view',
                'company_id' => 10,
                'type' => 2,
                'parent_id' => 232,
                'min_quantity' => 2,
                'thumbnail' => 0,
                'order_by' => 1,
                'created_at' => '2020-01-10 16:21:49',
                'updated_at' => '2020-01-10 16:21:49',
                'deleted_at' => NULL,
            ),
            177 => 
            array (
                'id' => 234,
                'name' => 'washroom required photo',
                'company_id' => 10,
                'type' => 1,
                'parent_id' => 0,
                'min_quantity' => 2,
                'thumbnail' => 1,
                'order_by' => 1,
                'created_at' => '2020-01-10 16:22:11',
                'updated_at' => '2020-01-10 16:22:11',
                'deleted_at' => NULL,
            ),
            178 => 
            array (
                'id' => 235,
                'name' => 'Additional Photos',
                'company_id' => 13,
                'type' => 3,
                'parent_id' => 0,
                'min_quantity' => 0,
                'thumbnail' => 0,
                'order_by' => 0,
                'created_at' => '2020-04-09 12:47:15',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}