<?php

use Illuminate\Database\Seeder;

class CmsModulsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cms_moduls')->delete();
        
        \DB::table('cms_moduls')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Notifications',
                'icon' => 'fa fa-cog',
                'path' => 'notifications',
                'table_name' => 'cms_notifications',
                'controller' => 'NotificationsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Privileges',
                'icon' => 'fa fa-cog',
                'path' => 'privileges',
                'table_name' => 'cms_privileges',
                'controller' => 'PrivilegesController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Privileges Roles',
                'icon' => 'fa fa-cog',
                'path' => 'privileges_roles',
                'table_name' => 'cms_privileges_roles',
                'controller' => 'PrivilegesRolesController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Users Management',
                'icon' => 'fa fa-users',
                'path' => 'users',
                'table_name' => 'cms_users',
                'controller' => 'AdminCmsUsersController',
                'is_protected' => 0,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Settings',
                'icon' => 'fa fa-cog',
                'path' => 'settings',
                'table_name' => 'cms_settings',
                'controller' => 'SettingsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Module Generator',
                'icon' => 'fa fa-database',
                'path' => 'module_generator',
                'table_name' => 'cms_moduls',
                'controller' => 'ModulsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Menu Management',
                'icon' => 'fa fa-bars',
                'path' => 'menu_management',
                'table_name' => 'cms_menus',
                'controller' => 'MenusController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Email Templates',
                'icon' => 'fa fa-envelope-o',
                'path' => 'email_templates',
                'table_name' => 'cms_email_templates',
                'controller' => 'EmailTemplatesController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Statistic Builder',
                'icon' => 'fa fa-dashboard',
                'path' => 'statistic_builder',
                'table_name' => 'cms_statistics',
                'controller' => 'StatisticBuilderController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'API Generator',
                'icon' => 'fa fa-cloud-download',
                'path' => 'api_generator',
                'table_name' => '',
                'controller' => 'ApiCustomController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Log User Access',
                'icon' => 'fa fa-flag-o',
                'path' => 'logs',
                'table_name' => 'cms_logs',
                'controller' => 'LogsController',
                'is_protected' => 1,
                'is_active' => 1,
                'created_at' => '2018-10-03 16:40:03',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'Subscription Plans',
                'icon' => 'fa fa-star',
                'path' => 'subscription',
                'table_name' => 'subscription',
                'controller' => 'AdminSubscriptionController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2018-11-01 15:02:22',
                'updated_at' => NULL,
                'deleted_at' => '2018-12-04 17:01:09',
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'App Users',
                'icon' => 'fa fa-user',
                'path' => 'user',
                'table_name' => 'user',
                'controller' => 'AdminUserController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 08:45:29',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:33:00',
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'Plants Management',
                'icon' => 'fa fa-glass',
                'path' => 'plants',
                'table_name' => 'plants',
                'controller' => 'AdminPlantsController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 12:47:24',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:33:09',
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'Units Management',
                'icon' => 'fa fa-glass',
                'path' => 'units',
                'table_name' => 'units',
                'controller' => 'AdminUnitsController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 12:50:13',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:33:18',
            ),
            15 => 
            array (
                'id' => 18,
                'name' => 'Floors Management',
                'icon' => 'fa fa-glass',
                'path' => 'floors',
                'table_name' => 'floors',
                'controller' => 'AdminFloorsController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 12:55:08',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:33:03',
            ),
            16 => 
            array (
                'id' => 19,
                'name' => 'Ports Management',
                'icon' => 'fa fa-glass',
                'path' => 'ports',
                'table_name' => 'ports',
                'controller' => 'AdminPortsController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 12:58:57',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:33:11',
            ),
            17 => 
            array (
                'id' => 20,
                'name' => 'Inventory Management',
                'icon' => 'fa fa-glass',
                'path' => 'inventory',
                'table_name' => 'inventory',
                'controller' => 'AdminInventoryController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 13:02:33',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:33:05',
            ),
            18 => 
            array (
                'id' => 21,
                'name' => 'Task Management',
                'icon' => 'fa fa-glass',
                'path' => 'task_management',
                'table_name' => 'task_management',
                'controller' => 'AdminTaskManagementController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 15:37:58',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-07 15:44:49',
            ),
            19 => 
            array (
                'id' => 22,
                'name' => 'Task Management',
                'icon' => 'fa fa-glass',
                'path' => 'task_management22',
                'table_name' => 'task_management',
                'controller' => 'AdminTaskManagement22Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-07 15:50:54',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:33:15',
            ),
            20 => 
            array (
                'id' => 23,
                'name' => 'App Users',
                'icon' => 'fa fa-user',
                'path' => 'cms_users',
                'table_name' => 'cms_users',
                'controller' => 'AdminCmsUsers1Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-01-28 16:41:27',
                'updated_at' => NULL,
                'deleted_at' => '2019-01-28 16:44:30',
            ),
            21 => 
            array (
                'id' => 24,
                'name' => 'Influencers',
                'icon' => 'fa fa-user',
                'path' => 'user24',
                'table_name' => 'user',
                'controller' => 'AdminUser24Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-02-20 20:15:22',
                'updated_at' => NULL,
                'deleted_at' => '2019-03-12 18:11:14',
            ),
            22 => 
            array (
                'id' => 25,
                'name' => 'Travelers',
                'icon' => 'fa fa-user',
                'path' => 'user25',
                'table_name' => 'user',
                'controller' => 'AdminUser25Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-02-20 20:17:42',
                'updated_at' => NULL,
                'deleted_at' => '2019-03-12 18:11:08',
            ),
            23 => 
            array (
                'id' => 26,
                'name' => 'Vendors',
                'icon' => 'fa fa-user',
                'path' => 'user26',
                'table_name' => 'user',
                'controller' => 'AdminUser26Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-02-20 20:30:46',
                'updated_at' => NULL,
                'deleted_at' => '2019-03-12 18:11:04',
            ),
            24 => 
            array (
                'id' => 27,
                'name' => 'App Users',
                'icon' => 'fa fa-users',
                'path' => 'user27',
                'table_name' => 'user',
                'controller' => 'AdminUser27Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-02-20 20:37:43',
                'updated_at' => NULL,
                'deleted_at' => '2019-03-12 18:13:18',
            ),
            25 => 
            array (
                'id' => 28,
                'name' => 'Local',
                'icon' => 'fa fa-user',
                'path' => 'user28',
                'table_name' => 'user',
                'controller' => 'AdminUser281Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-02-21 22:25:22',
                'updated_at' => NULL,
                'deleted_at' => '2019-03-12 18:11:11',
            ),
            26 => 
            array (
                'id' => 29,
                'name' => 'Employees',
                'icon' => 'fa fa-users',
                'path' => 'employees',
                'table_name' => 'user',
                'controller' => 'AdminEmployeesController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-03-19 14:45:20',
                'updated_at' => NULL,
                'deleted_at' => '2019-06-03 16:18:25',
            ),
            27 => 
            array (
                'id' => 30,
                'name' => 'Customers',
                'icon' => 'fa fa-users',
                'path' => 'customer',
                'table_name' => 'customer',
                'controller' => 'AdminCustomerController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-03-20 14:16:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 31,
                'name' => 'Offers',
                'icon' => 'fa fa-gift',
                'path' => 'offer',
                'table_name' => 'offer',
                'controller' => 'AdminOfferController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-03-20 15:30:18',
                'updated_at' => NULL,
                'deleted_at' => '2019-06-03 16:18:20',
            ),
            29 => 
            array (
                'id' => 32,
                'name' => 'Testimonials',
                'icon' => 'fa fa-glass',
                'path' => 'testimonials',
                'table_name' => 'testimonials',
                'controller' => 'AdminTestimonials1Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-03-26 04:03:23',
                'updated_at' => NULL,
                'deleted_at' => '2019-03-26 13:36:46',
            ),
            30 => 
            array (
                'id' => 33,
                'name' => 'Testimonial',
                'icon' => 'fa fa-glass',
                'path' => 'testimonials33',
                'table_name' => 'testimonials',
                'controller' => 'AdminTestimonials33Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-03-26 13:37:31',
                'updated_at' => NULL,
                'deleted_at' => '2019-06-03 16:18:15',
            ),
            31 => 
            array (
                'id' => 34,
                'name' => 'Products',
                'icon' => 'fa fa-archive',
                'path' => 'product',
                'table_name' => 'product',
                'controller' => 'AdminProductController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-06-03 16:23:30',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 35,
                'name' => 'Users',
                'icon' => 'fa fa-users',
                'path' => 'user',
                'table_name' => 'user',
                'controller' => 'AdminUser1Controller',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-06-13 14:08:56',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 36,
                'name' => 'Product Requests',
                'icon' => 'fa fa-glass',
                'path' => 'product_request',
                'table_name' => 'product_request',
                'controller' => 'AdminProductRequestController',
                'is_protected' => 0,
                'is_active' => 0,
                'created_at' => '2019-06-13 15:22:06',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}