<?php

use Illuminate\Database\Seeder;

class NotificationTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('notification')->delete();
        
        \DB::table('notification')->insert(array (
            0 => 
            array (
                'id' => 1,
                'notification_identifier_id' => 1,
                'actor_id' => 1,
                'target_id' => 2,
                'reference_id' => 5,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'daniel noah',
                'description' => 'Developer  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-10 10:28:19',
                'updated_at' => '2019-11-13 11:06:38',
            ),
            1 => 
            array (
                'id' => 2,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 6,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'project retort',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-10 10:28:56',
                'updated_at' => '2019-10-11 17:56:51',
            ),
            2 => 
            array (
                'id' => 3,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 7,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'project retort',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-10 10:29:24',
                'updated_at' => '2019-10-11 17:56:47',
            ),
            3 => 
            array (
                'id' => 4,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 13,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'stark',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 13:54:08',
                'updated_at' => '2019-11-13 11:54:38',
            ),
            4 => 
            array (
                'id' => 5,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 14,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Dev Pro',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 14:09:02',
                'updated_at' => '2019-11-13 11:54:35',
            ),
            5 => 
            array (
                'id' => 6,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 15,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Dev Pro',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 14:31:36',
                'updated_at' => '2019-11-13 11:54:34',
            ),
            6 => 
            array (
                'id' => 7,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 16,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Dev Pro',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 14:33:50',
                'updated_at' => '2019-11-13 11:54:31',
            ),
            7 => 
            array (
                'id' => 8,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 17,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Dev Pro',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 14:35:42',
                'updated_at' => '2019-10-14 14:47:32',
            ),
            8 => 
            array (
                'id' => 9,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 18,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'abc',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 14:38:49',
                'updated_at' => '2019-10-14 14:41:59',
            ),
            9 => 
            array (
                'id' => 10,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 19,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'xyz',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 14:54:33',
                'updated_at' => '2019-11-13 11:36:37',
            ),
            10 => 
            array (
                'id' => 11,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 23,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'rob',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 15:14:41',
                'updated_at' => '2019-11-13 10:34:30',
            ),
            11 => 
            array (
                'id' => 12,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 25,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'bravo',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:00:44',
                'updated_at' => '2019-10-11 17:49:47',
            ),
            12 => 
            array (
                'id' => 13,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 26,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'bravo',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:01:45',
                'updated_at' => '2019-10-11 17:48:32',
            ),
            13 => 
            array (
                'id' => 14,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 27,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:49:19',
                'updated_at' => '2019-10-11 17:50:50',
            ),
            14 => 
            array (
                'id' => 15,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 28,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:04',
                'updated_at' => '2019-10-11 17:51:04',
            ),
            15 => 
            array (
                'id' => 16,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 29,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:04',
                'updated_at' => '2019-10-11 17:51:04',
            ),
            16 => 
            array (
                'id' => 17,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 30,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:04',
                'updated_at' => '2019-10-11 17:51:04',
            ),
            17 => 
            array (
                'id' => 18,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 31,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:05',
                'updated_at' => '2019-10-11 17:51:05',
            ),
            18 => 
            array (
                'id' => 19,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 32,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:05',
                'updated_at' => '2019-10-11 17:51:05',
            ),
            19 => 
            array (
                'id' => 20,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 33,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:05',
                'updated_at' => '2019-10-11 17:51:05',
            ),
            20 => 
            array (
                'id' => 21,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 34,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:05',
                'updated_at' => '2019-10-11 17:51:05',
            ),
            21 => 
            array (
                'id' => 22,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 35,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:05',
                'updated_at' => '2019-10-11 17:51:05',
            ),
            22 => 
            array (
                'id' => 23,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 36,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:06',
                'updated_at' => '2019-10-11 17:51:06',
            ),
            23 => 
            array (
                'id' => 24,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 37,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:06',
                'updated_at' => '2019-10-11 17:51:06',
            ),
            24 => 
            array (
                'id' => 25,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 38,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:06',
                'updated_at' => '2019-10-11 17:51:06',
            ),
            25 => 
            array (
                'id' => 26,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 39,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:06',
                'updated_at' => '2019-10-11 17:51:06',
            ),
            26 => 
            array (
                'id' => 27,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 40,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:06',
                'updated_at' => '2019-10-11 17:51:53',
            ),
            27 => 
            array (
                'id' => 28,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 41,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:51:06',
                'updated_at' => '2019-10-11 17:53:44',
            ),
            28 => 
            array (
                'id' => 29,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 42,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Project Rabit hole',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 17:58:37',
                'updated_at' => '2019-11-13 11:36:41',
            ),
            29 => 
            array (
                'id' => 30,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 43,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Demo Project',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-11 18:02:41',
                'updated_at' => '2019-10-11 18:03:15',
            ),
            30 => 
            array (
                'id' => 31,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 46,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:22:00',
                'updated_at' => '2019-11-13 10:36:59',
            ),
            31 => 
            array (
                'id' => 32,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 47,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:10',
                'updated_at' => '2019-11-13 10:58:33',
            ),
            32 => 
            array (
                'id' => 33,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 48,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_2',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:10',
                'updated_at' => '2019-10-15 08:23:10',
            ),
            33 => 
            array (
                'id' => 34,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 49,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:34',
                'updated_at' => '2019-10-15 08:23:34',
            ),
            34 => 
            array (
                'id' => 35,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 50,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:35',
                'updated_at' => '2019-10-15 08:23:35',
            ),
            35 => 
            array (
                'id' => 36,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 51,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:35',
                'updated_at' => '2019-10-15 08:23:35',
            ),
            36 => 
            array (
                'id' => 37,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 52,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:36',
                'updated_at' => '2019-10-15 08:23:36',
            ),
            37 => 
            array (
                'id' => 38,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 53,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:36',
                'updated_at' => '2019-10-15 08:23:36',
            ),
            38 => 
            array (
                'id' => 39,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 54,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:37',
                'updated_at' => '2019-10-15 08:23:37',
            ),
            39 => 
            array (
                'id' => 40,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 55,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:38',
                'updated_at' => '2019-10-15 08:26:59',
            ),
            40 => 
            array (
                'id' => 41,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 56,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:39',
                'updated_at' => '2019-11-13 11:51:30',
            ),
            41 => 
            array (
                'id' => 42,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 57,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:40',
                'updated_at' => '2019-10-15 08:23:40',
            ),
            42 => 
            array (
                'id' => 43,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 58,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:40',
                'updated_at' => '2019-11-13 13:50:29',
            ),
            43 => 
            array (
                'id' => 44,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 59,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_4',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:23:41',
                'updated_at' => '2019-11-13 13:46:35',
            ),
            44 => 
            array (
                'id' => 45,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 60,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project 5',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:35',
                'updated_at' => '2019-11-13 13:49:52',
            ),
            45 => 
            array (
                'id' => 46,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 61,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project 5',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:35',
                'updated_at' => '2019-11-13 11:54:44',
            ),
            46 => 
            array (
                'id' => 47,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 62,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:53',
                'updated_at' => '2019-10-15 08:24:53',
            ),
            47 => 
            array (
                'id' => 48,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 63,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:54',
                'updated_at' => '2019-10-15 08:24:54',
            ),
            48 => 
            array (
                'id' => 49,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 64,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:55',
                'updated_at' => '2019-10-15 08:24:55',
            ),
            49 => 
            array (
                'id' => 50,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 65,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:55',
                'updated_at' => '2019-10-15 08:24:55',
            ),
            50 => 
            array (
                'id' => 51,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 66,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:56',
                'updated_at' => '2019-11-13 13:40:27',
            ),
            51 => 
            array (
                'id' => 52,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 67,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:57',
                'updated_at' => '2019-11-06 16:59:40',
            ),
            52 => 
            array (
                'id' => 53,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 68,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:57',
                'updated_at' => '2019-11-13 11:38:37',
            ),
            53 => 
            array (
                'id' => 54,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 69,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:58',
                'updated_at' => '2019-11-13 12:27:41',
            ),
            54 => 
            array (
                'id' => 55,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 70,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:24:59',
                'updated_at' => '2019-11-13 11:36:22',
            ),
            55 => 
            array (
                'id' => 56,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 71,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:25:00',
                'updated_at' => '2019-11-13 11:08:54',
            ),
            56 => 
            array (
                'id' => 57,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 4,
                'reference_id' => 72,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'U Project_6',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 08:25:00',
                'updated_at' => '2019-11-13 11:41:39',
            ),
            57 => 
            array (
                'id' => 58,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 6,
                'reference_id' => 73,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'ab project',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-15 17:18:55',
                'updated_at' => '2019-10-15 17:19:48',
            ),
            58 => 
            array (
                'id' => 59,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 81,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'final project',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-23 13:10:28',
                'updated_at' => '2019-10-23 17:44:59',
            ),
            59 => 
            array (
                'id' => 60,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 82,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'fire project',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-23 13:44:25',
                'updated_at' => '2019-10-23 17:44:48',
            ),
            60 => 
            array (
                'id' => 61,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 83,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'cold',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-23 13:57:13',
                'updated_at' => '2019-10-23 17:44:40',
            ),
            61 => 
            array (
                'id' => 62,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 86,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'super',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-10-23 17:55:40',
                'updated_at' => '2019-11-06 12:38:43',
            ),
            62 => 
            array (
                'id' => 63,
                'notification_identifier_id' => 1,
                'actor_id' => 13,
                'target_id' => 14,
                'reference_id' => 88,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Test Project',
                'description' => 'Test  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-10-28 07:46:19',
                'updated_at' => '2019-10-28 07:46:19',
            ),
            63 => 
            array (
                'id' => 64,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 89,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'thunder',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-11-05 17:50:09',
                'updated_at' => '2019-11-06 12:38:39',
            ),
            64 => 
            array (
                'id' => 65,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 17,
                'reference_id' => 93,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'clean',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-11-08 19:48:45',
                'updated_at' => '2019-11-11 16:13:24',
            ),
            65 => 
            array (
                'id' => 66,
                'notification_identifier_id' => 1,
                'actor_id' => 18,
                'target_id' => 19,
                'reference_id' => 95,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'new',
                'description' => 'omi  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2019-11-12 12:47:37',
                'updated_at' => '2019-11-12 12:47:37',
            ),
            66 => 
            array (
                'id' => 67,
                'notification_identifier_id' => 1,
                'actor_id' => 20,
                'target_id' => 21,
                'reference_id' => 96,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'winter',
                'description' => 'jon snow assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-11-13 12:13:59',
                'updated_at' => '2019-11-13 16:05:49',
            ),
            67 => 
            array (
                'id' => 68,
                'notification_identifier_id' => 1,
                'actor_id' => 22,
                'target_id' => 23,
                'reference_id' => 99,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'Beta 1',
                'description' => 'Paul Lewis assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-11-13 20:28:04',
                'updated_at' => '2019-11-13 22:46:33',
            ),
            68 => 
            array (
                'id' => 69,
                'notification_identifier_id' => 1,
                'actor_id' => 18,
                'target_id' => 26,
                'reference_id' => 106,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'import',
                'description' => 'omi  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-11-26 15:25:39',
                'updated_at' => '2019-11-26 18:41:24',
            ),
            69 => 
            array (
                'id' => 70,
                'notification_identifier_id' => 1,
                'actor_id' => 18,
                'target_id' => 27,
                'reference_id' => 107,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'boi',
                'description' => 'omi  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-12-02 15:20:26',
                'updated_at' => '2019-12-02 16:40:13',
            ),
            70 => 
            array (
                'id' => 71,
                'notification_identifier_id' => 1,
                'actor_id' => 28,
                'target_id' => 29,
                'reference_id' => 109,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'final project',
                'description' => 'omi  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2019-12-05 12:33:27',
                'updated_at' => '2019-12-05 12:44:53',
            ),
            71 => 
            array (
                'id' => 72,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 113,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'happ new year',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2020-01-02 13:09:09',
                'updated_at' => '2020-01-06 19:17:53',
            ),
            72 => 
            array (
                'id' => 73,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 114,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'now pro',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2020-01-07 15:23:19',
                'updated_at' => '2020-01-08 18:46:53',
            ),
            73 => 
            array (
                'id' => 74,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 124,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'bottle',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2020-01-17 17:24:50',
                'updated_at' => '2020-01-17 18:47:51',
            ),
            74 => 
            array (
                'id' => 75,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 145,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'test 3',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 0,
                'is_viewed' => 0,
                'created_at' => '2020-01-20 19:41:22',
                'updated_at' => '2020-01-20 19:41:22',
            ),
            75 => 
            array (
                'id' => 76,
                'notification_identifier_id' => 1,
                'actor_id' => 3,
                'target_id' => 12,
                'reference_id' => 148,
                'reference_module' => 'project',
                'type' => '',
                'title' => 'shark',
                'description' => 'arya  assigned you a project.',
                'is_notify' => 0,
                'is_read' => 1,
                'is_viewed' => 0,
                'created_at' => '2020-01-21 16:33:49',
                'updated_at' => '2020-01-21 16:42:19',
            ),
        ));
        
        
    }
}